default: &default
  adapter: postgresql
  encoding: 'utf8'
  pool: 5
  port: 5432
  host: 'localhost'
  username: postgres
  password: postgres@123

development:
  <<: *default
  database: ror_infakt_dev

test:
  <<: *default
  database: ror_infakt_test

production:
  <<: *default
  database: ror_infakt_prod
